### ISSUE TITLE
Time for LAST index build

### ISSUE THREAD

**Issue by Lagkouvardos** [fungs/taxator-tk#45]
I first would like to thank you for the effort to provide the community a reliable composition based metagenomic taxonomic classifier.  On samples with many unknown organisms the similarity based approaches fail to classify up to 90% of the contigs. 

I setup your programs and download the most resent (and biggest) refpack. I start the LAST index building 3 days ago and it is still stuck on building it. So my question is:

#### How long is the normal run time for building the LAST  index?

The machine specs are Ubuntu 128 Gb RAM, 24 threads 4 Tb disk

**Comment by fungs** [comment]
Dear @Lagkouvardos,

thanks for your report.

> Official description: taxator-tk is an algorithm and the accompanying software, which performs taxonomic sequence assignment by fast approximate determination of evolutionary neighbors from sequence similarities.

First of all, taxator-tk does not use nucleotide sequence composition but alignments/similarity. It will therefore most likely deliver similar results in terms of the sensitivity/recall (percentage of data being assigned). Recall might be even lower than with other tools because the software focuses on a high precision in classification. That being said, you should try the BLAST pipeline because index building there is much faster. If the results with parameter `blast_algorithm=blastn` look good, you can consider using the LAST index but it only makes sense when you have many data to process. **The index building in LAST is single-threaded and might take up to a month for the latest refpack!** This is the major drawback with using LAST, so you can as well invest that time into doing the alignments with BLAST+.

If you have an assembly (>> 1000 bp) from an environment with novel OTUs (I'm guessing this from your low recall), you could give our sister tool PhyloPythiaS+ (Gregor et al.) a try. It is a composition-based classifier with an automatized training procedure and PhyloPythia(S) has proven to work reliably for many years and environments.

Gruß Johannes

**Comment by Lagkouvardos** [comment]
Thanks Johanes,

I will try PPS+, you can close this issue.
