### ISSUE TITLE
'boost::exception_detail::clone_impl<FileNotFound>'

### ISSUE THREAD

**Issue by rotoscan** [fungs/taxator-tk#60]
Hello,

I am trying to get a taxonomy assignment on a bin of contigs I generated. I used a command you suggested here (https://github.com/fungs/taxator-tk/blob/master/USAGE.md), but I am getting an error.

### Command:
 $ blastn -task blastn -db /data/msb/tools/taxator-tk/taxator-tk_1.3.3e-64bit/DATABASES/microbial-full_20150430/microbial-full_20150430_database -outfmt '6 qseqid qstart qend qlen sseqid sstart send bitscore evalue nident length' -query A_euk_cct.bin.29.fa -num_threads 8 | /data/msb/tools/taxator-tk/taxator-tk_1.3.3e-64bit/bin/taxator -g acc_taxid.tax -q A_euk_cct.bin.29.fa -v A_euk_cct.bin.29.fa.fai -f /data/msb/tools/taxator-tk/taxator-tk_1.3.3e-64bit/DATABASES/microbial-full_20150430/refdata.fna -i /data/msb/tools/taxator-tk/taxator-tk_1.3.3e-64bit/DATABASES/microbial-full_20150430/refdata.fna.fai | sort -k1,1 > my.predictions.gff3

### Errror:
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<FileNotFound>'
  what():  could not find file

I wonder what could be the mistake. I would appreciate for any given help. Thank you!

Best,
Rodolfo

**Comment by fungs** [comment]
Apparently, a file is missing, the message is pretty clear. Try to run with `-num_threads 1`, it might give you better error messages as the multi-threaded implementation seems to cover some error messages.

If you want to build custom commands, please take a look at the master scripts to see how commands are linked together. Did you try the binning-blast.bash script and read the README in the extended binary distribution package?

For example, some versions of BLAST fill the tab-separated output with spaces, so they must be removed from the output (tr -d ' '). But this doesn't seem to be the problem here.

If the query is small, just remove the `-v` option and taxator-tk will load the sequences into memory.

**Comment by fungs** [comment]
microbial-full_20150430/microbial-full_20150430 seems suspicious to me. It's best to follow the refpack definition as implemented in the extended package scripts, e.g. use index-blast.sh to build a blast database for a refpack.

**Comment by rotoscan** [comment]
Hello fungs,

apparently I screwed things up during my installation of the database. I have followed your instructions and it worked nicely. I have my output. Sorry for the trouble and thanks for the attention anyway. =)

Best,
Rodolfo

**Comment by fungs** [comment]
Glad you did it! Note, that if you want to tweak something, it might be worth using a custom refpack or an updated refseq release as refpack in taxator-tk. Future releases will allow faster alignment and updated refpacks are to come as well.
